create table patient_appointments_book (
   id               number
      generated by default on null as identity
   primary key,
   patient_id       number not null,
   appointment_for  varchar2(50),
   dep_name         varchar2(100),
   has_insurance    varchar2(10),
   reason           varchar2(400),
   symptoms         varchar2(400),
   uploaded_file    varchar2(255),
   consult_type     varchar2(50),
   clinic_name      varchar2(200),
   appointment_date date,
   appointment_time varchar2(20),
   payment_method   varchar2(50),
   total_amount     number,
   created_at       timestamp default current_timestamp
);