create table vital_signs (
   id                number
      generated by default as identity
   primary key,
   patient_id        number
      references patients ( id ),
   heart_rate        number,
   body_temp         number,
   glucose_level_min number,
   glucose_level_max number,
   spo2              number,
   blood_pressure    varchar2(10),
   bmi               number,
   report_date       date
);