create table patient_appointments (
   id                number
      generated by default on null as identity
   primary key,
   patient_id        number not null,
   appointment_for   varchar2(50),
   dependent_name    varchar2(100),
   has_insurance     varchar2(10),
   reason            varchar2(400),
   symptoms          varchar2(200),
   uploaded_file     varchar2(255),
   consultation_type varchar2(50),
   created_at        date default sysdate
);