create table patient_appointments_book (
   id               number
      generated by default on null as identity
   primary key,
   patient_id       number not null,
   appointment_for  varchar2(20),
   dep_name         varchar2(100),
   has_insurance    varchar2(10),
   reason           varchar2(500),
   symptoms         varchar2(500),
   uploaded_file    varchar2(255),
   consult_type     varchar2(50),
   clinic_name      varchar2(100),
   appointment_date date,
   appointment_time varchar2(10),
   payment_method   varchar2(50),
   total_amount     number,
   first_name       varchar2(100),
   last_name        varchar2(100),
   phone            varchar2(20),
   email            varchar2(200),
   service_name     varchar2(100),
   created_at       timestamp default current_timestamp
);